 <div class="newpost"><a href="/<?php echo $this->_url_pathAry[1];?>/newpost/">新增主題</a></div>
<br>
<table align="center" border="0" width="700" cellpadding ="0" cellspacing="0">
	<tr>
		<th class="listTitle">標題</th>
		<th width="80" class="listTitle">回覆數</th>
		<th width="100" class="listTitle">最後發表</th>
	</tr><?php
	$data = $view->getData();
	foreach ($data[0] as $key => $val):?>
	<tr<?php if ($key % 2 == 1):?> style="background-color:#D7D7D7;"<?php endif;?>>
		<td><a href="/exp/detail/pageNo/<?php echo $data["PAGENO"]?>/id/<?php echo $val["ID"];?>/"><?php echo $val["TITLE"];?></a></td>
		<td align="right"><?php echo $val["COUNTS"];?>&nbsp;&nbsp;<br><font size="1"><?php echo $val["NAME"];?></font></td>
		<td align="center"><?php echo $val["LASTRTIME"];?></td>
	</tr>
	<?php endforeach;?>
</table>
<div style="clear:both;height:50px;"></div>
<div class="pageList"><?php echo $data[1];?></div>