<?php $data = $view->getData();?>
<script type="text/javascript">
	$(function(){
		setNewDateSelect("#wdate");
	});
</script>
<link rel="StyleSheet" href="/styles/base/jquery.ui.datepicker.css" type="text/css">
<link rel="StyleSheet" href="/styles/base/jquery.ui.theme.css" type="text/css">
<div id="SITE_TITLE"><?php echo $this->_chkf->getFuName($this->_url_pathAry[2]);?></div>
<div class="new_modify"><a href="<?php echo $data -> BACKURL;?>">回清單</a></div>
<div id="modify_detail">
	<form action="<?php echo preg_replace("/album_modify/", "update", $_SERVER["REQUEST_URI"]);?>" method="post" name="modify_form" id="modify_form" enctype="multipart/form-data">
	<input type="hidden" name="parent_id" id="parent_id" value="<?php echo $data->PARENT_ID;?>">
	<table width="98%">
		<tr>
			<td></td>
			<td align="right">標題&nbsp;</td>
			<td><input type="text" name="title" id="title" value="<?php echo $data->TITLE;?>"></td>
			<td></td>
		</tr>
		<tr>
			<td><?php $fieldName = "IMAGE";?></td>
			<td align="right">清單圖示&nbsp;</td>
			<td>
				<input type="file" name="<?php echo strtolower($fieldName);?>" id="<?php echo strtolower($fieldName);?>" value=""><br>
				<?php if (strcmp($data->$fieldName, "")):?><div>目前的檔案:<?php echo $data->$fieldName;?><br>
				<?php 
				$fileAry = explode(".", $data->$fieldName);
				if (in_array($fileAry[1], array("jpg","png","gif","bmp", "jpeg"))):?>
				<img src="/public/album/<?php echo $data->$fieldName;?>" width="100">
				<a href="/admin/album/page_name/delimg/field_name/<?php echo $fieldName;?>/id/<?php echo $data->ID;?>/">刪除檔案</a>
				<?php endif;?>
				</div><?php endif;?>
			</td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td align="right">日期&nbsp;</td>
			<td><input type="text" name="wdate" id="wdate" value="<?php echo $data->WDATE;?>"></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td align="right">內容&nbsp;</td>
			<td><textarea rows="6" cols="60" name="memoirs" id="memoirs"><?php echo $data->MEMOIRS;?></textarea></td>
			<td></td>
		</tr>
		<?php for ($x = 1;$x < 3;$x++):$fieldName = "FILE" . $x;?>
		<tr>
			<td></td>
			<td align="right">檔案上傳<?php echo $x;?>&nbsp;</td>
			<td>
				<input type="file" name="<?php echo strtolower($fieldName);?>" id="<?php echo strtolower($fieldName);?>" value=""><br>
				<?php if (strcmp($data->$fieldName, "")):?><div>目前的檔案:<?php echo $data->$fieldName;?><br>
				<?php 
				$fileAry = explode(".", $data->$fieldName);
				if (in_array($fileAry[1], array("jpg","png","gif","bmp", "jpeg"))):?>
				<img src="/public/album/<?php echo $data->$fieldName;?>" width="100">
				<a href="/admin/album/page_name/delimg/field_name/<?php echo $fieldName;?>/id/<?php echo $data->ID;?>/">刪除檔案</a>
				<?php endif;?>
				</div><?php endif;?>
			</td>
			<td></td>
		</tr>
		<?php endfor;?>
		<tr>
			<td></td>
			<td align="right">顯示&nbsp;</td>
			<td><input type="radio" name="active" id="active" value="Y"<?php if ($data->ACTIVE == "Y" || $data->ACTIVE == ""):?> checked<?php endif;?>> 啟用 <input type="radio" name="active" id="active" value="N"<?php if ($data->ACTIVE == "N"):?> checked<?php endif;?>> 開閉</td>
			<td></td>
		</tr>
		<tr>
			<td colspan="4" align="center"><input type="submit" value="儲存">&nbsp;&nbsp;<input type="reset" value="重填"></td>
		</tr>
	</table>
	</form>
</div>