<?php $data = $view->getData();?>
<div id="SITE_TITLE"><?php echo $this->_chkf->getFuName($this->_url_pathAry[2]);?></div>
<div class="new_modify"><?php if ($data["PARENT_ID"] > 0):?><a href="/admin/album/page_name/album_modify/pageNo/<?php echo $data["PAGENO"];?>/parent_id/<?php echo $data["PARENT_ID"];?>/id/-/">新增一筆</a><?php else:?><a href="/admin/album/page_name/albumt_modify/pageNo/<?php echo $data["PAGENO"];?>/parent_id/-/">新增新類別</a><?php endif;?></div>
<ul class="news_list">
<?php 
foreach ($data[0] as $val):?>
	<li><?php if ($data["PARENT_ID"] > 0):?><a href="/admin/album/page_name/album_modify/pageNo/<?php echo $data["PAGENO"];?>/parent_id/<?php echo $val["PARENT_ID"];?>/id/<?php echo $val["ID"];?>/"><?php else:?>[ <a href="/admin/album/page_name/albumt_modify/pageNo/<?php echo $data["PAGENO"];?>/id/<?php echo $val["ID"];?>/">編輯</a> ] <a href="/admin/album/page_name/album_list/pageNo/<?php echo $data["PAGENO"];?>/parent_id/<?php echo $val["ID"];?>/"><?php endif;?><?php echo $val["TITLE"];?></a></li>
<?php endforeach;?>
</ul>
<div class="clear_div"></div>
<div class="pageList"><?php echo $data[1];?></div>