<?php $data = $view->getData();?>
<div id="SITE_TITLE"><?php echo $this->_chkf->getFuName($this->_url_pathAry[2]);?></div>
<div class="new_modify"><a href="<?php echo $data -> BACKURL;?>">回清單</a></div>
<div id="modify_detail">
	<form action="<?php echo preg_replace("/download_modify/", "update", $_SERVER["REQUEST_URI"]);?>" method="post" name="modify_form" id="modify_form" enctype="multipart/form-data">
	<table width="98%">
		<tr>
			<td></td>
			<td align="right">標題&nbsp;</td>
			<td><input type="text" name="title" id="title" value="<?php echo $data->TITLE;?>"></td>
			<td></td>
		</tr>
		<?php for ($x = 1;$x < 3;$x++):$fieldName = "FILE" . $x;?>
		<tr>
			<td></td>
			<td align="right">檔案上傳<?php echo $x;?>&nbsp;</td>
			<td>
				<input type="file" name="<?php echo strtolower($fieldName);?>" id="<?php echo strtolower($fieldName);?>" value=""><br>
				<?php if (strcmp($data->$fieldName, "")):?><div>目前的檔案:<?php echo $data->$fieldName;?><br>
				<?php 
				$fileAry = explode(".", $data->$fieldName);
				if (in_array($fileAry[1], array("jpg","png","gif","bmp", "jpeg"))):?>
				<img src="/public/download/<?php echo $data->$fieldName;?>" width="100">
				<?php endif;?><a href="/admin/download/page_name/delimg/field_name/<?php echo $fieldName;?>/id/<?php echo $data->ID;?>/">刪除檔案</a>
				</div><?php endif;?>
			</td>
			<td></td>
		</tr>
		<?php endfor;?>
		<tr>
			<td></td>
			<td align="right">顯示&nbsp;</td>
			<td><input type="radio" name="active" id="active" value="Y"<?php if ($data->ACTIVE == "Y"):?> checked<?php endif;?>> 啟用 <input type="radio" name="active" id="active" value="N"<?php if ($data->ACTIVE == "N"):?> checked<?php endif;?>> 開閉</td>
			<td></td>
		</tr>
		<tr>
			<td colspan="4" align="center"><input type="submit" value="儲存">&nbsp;&nbsp;<input type="reset" value="重填"></td>
		</tr>
	</table>
	</form>
</div>