<style type="text/css">
th{
	color: #333333;
}
</style>
<?php $data = $view->getData();?>
<div id="SITE_TITLE" class="ftitle_bg"><?php echo $this->_chkf->getFuName($this->_url_pathAry[2]);?></div>
<div class="new_modify"><a href="<?php echo $data -> BACKURL;?>">回清單</a></div>
<div id="modify_detail">
	<form action="<?php echo preg_replace("/exp_modify/", "update", $_SERVER["REQUEST_URI"]);?>" method="post" name="modify_form" id="modify_form">
	<table width="98%">
		<tr>
			<td></td>
			<th align="right">主題:</th>
			<td align="left"><input type="text" name="title" id="title" value="<?php echo $data->TITLE;?>" style="width: 500px;"></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<th align="right">暱稱:</th>
			<td align="left"><input type="text" name="name" id="name" value="<?php echo $data->NAME;?>" style="width: 500px;"></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<th align="right">留言內容:</th>
			<td align="left"><textarea rows="10" cols="60" name="memoirs" id="memoirs" style="width: 500px;"><?php echo $data->MEMOIRS;?></textarea></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td align="right">顯示&nbsp;</td>
			<td><input type="radio" name="active" id="active" value="Y"<?php if ($data->ACTIVE == "Y" || $data->ACTIVE == ""):?> checked<?php endif;?>> 啟用 <input type="radio" name="active" id="active" value="N"<?php if ($data->ACTIVE == "N"):?> checked<?php endif;?>> 開閉</td>
			<td></td>
		</tr>
		<tr>
			<td colspan="4" align="center"><input type="submit" value="儲存">&nbsp;&nbsp;<input type="reset" value="重填"></td>
		</tr>
	</table>
	</form>
</div>