<div id="login_main">
	<div class="title">後台管理系統登入</div>
	<form action="/admin/login/" method="post" name="login_form" id="login_form"><input type="hidden" name="action" id="action" value="login">
		<div class="login_div">帳號: <input type="text" name="login_id" id="login_id" value=""></div>
		<div class="login_div">密碼: <input type="password" name="login_passwd" id="login_passwd" value=""></div>
		<div class="login_div"><input type="submit" value="登入"> <input type="reset" value="重設"></div>
	</form>
</div>