<?php $data = $view->getData();?>
<div id="SITE_TITLE"><?php echo $this->_chkf->getFuName($this->_url_pathAry[2]);?></div>
<div class="new_modify"><a href="/admin/member/page_name/member_modify/pageNo/<?php echo $data["PAGENO"];?>/id/-/">新增一筆</a></div>
<ul class="news_list user_list">
<?php 
foreach ($data[0] as $val):?>
	<li>[<?php echo $val["USER_ID"];?>] <a href="/admin/member/page_name/member_modify/pageNo/<?php echo $data["PAGENO"];?>/user_id/<?php echo $val["USER_ID"];?>/"><?php echo $val["USER_NAME"];?></a></li>
<?php endforeach;?>
</ul>
<div class="clear_div"></div>
<div class="pageList"><?php echo $data[1];?></div>