<div id="SITE_TITLE"><?php echo $this->_chkf->getFuName($this->_url_pathAry[1]);?></div>
<ul class="news_list">
<?php 
$data = $view->getData();
foreach ($data[0] as $val):?>
	<li>[<?php echo $val["WDATE"];?>] <a href="/news/detail/id/<?php echo $val["ID"];?>"><?php echo $val["TITLE"];?></a></li>
<?php endforeach;?>
</ul>
<div style="clear:both;"></div>
<div class="pageList"><?php echo $data[1];?></div>