<div id="main_album">
	<?php $data = $view->getData();
	foreach ($data[0] as $val):?>
	<div class="album_div">
		<div class="album_img"><a href="/album/mlist/parent_id/<?php echo $val["ID"];?>/"><img src="/public/album/<?php echo $val["IMAGE"];?>" width="200"></a></div>
		<div class="album_title"><a href="/album/mlist/parent_id/<?php echo $val["ID"];?>/"><?php echo $val["TITLE"];?></a></div>
	</div>
	<?php endforeach;?>
</div>
<div style="clear:both;height:50px;"></div>
<div class="pageList"><?php echo $data[1];?></div>