<html>
	<head>
		<title><?php echo $this->siteDatas -> SITE_CONFIG -> TITLE;?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php foreach ($this -> _controllCss as $cssFile):?><link rel="StyleSheet" href="/styles/<?php echo $cssFile;?>.css" type="text/css"><?php endforeach;?>
		<?php foreach ($this -> _controllJs as $jsFile):?><script type="text/javascript" src="<?php echo ((strtolower(substr($jsFile, 0, 4)) == "http") ? $jsFile : "/scripts/" . $jsFile);?>.js"></script><?php endforeach;?>
		<script type="text/javascript">
		$(function(){
			var weeksAry = new Array("星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六");
			var chineseDate = "<?php echo date("Y年m月d日");?>(" + weeksAry[<?php echo date(w);?>] + ") " + LunarDate.GetLunarDay(<?php echo date("Y, m, d");?>);
			$("#cdate").html(chineseDate);

			$(".lits").mouseover(function(){
				$(this).css("background-color", "#80A1E4");
			}).mouseout(function(){
				$(this).css("background-color", "#2468F2");
			}).click(function(){
				window.location.href = $(this).find("a").first().attr("href");
			});

			$("#main_menu").find("li").each(function(){
				$(this).mouseover(function(){
					$(this).attr("class", "btn_bg2 bucolor div_maru");
				}).mouseout(function(){
					$(this).attr("class", "btn_bg whcolor div_maru");
				});
			});
		});
		</script>
		<style type="text/css">
		.linksList ul li.lit{
			background: #7d7e7d; /* Old browsers */
			/* IE9 SVG, needs conditional override of 'filter' to 'none' */
			background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzdkN2U3ZCIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMwZTBlMGUiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
			background: -moz-linear-gradient(top,  #7d7e7d 0%, #0e0e0e 100%); /* FF3.6+ */
			background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#7d7e7d), color-stop(100%,#0e0e0e)); /* Chrome,Safari4+ */
			background: -webkit-linear-gradient(top,  #7d7e7d 0%,#0e0e0e 100%); /* Chrome10+,Safari5.1+ */
			background: -o-linear-gradient(top,  #7d7e7d 0%,#0e0e0e 100%); /* Opera 11.10+ */
			background: -ms-linear-gradient(top,  #7d7e7d 0%,#0e0e0e 100%); /* IE10+ */
			background: linear-gradient(to bottom,  #7d7e7d 0%,#0e0e0e 100%); /* W3C */
			filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#7d7e7d', endColorstr='#0e0e0e',GradientType=0 ); /* IE6-8 */
		}
		#main_link{
			background: #fcecfc; /* Old browsers */
			/* IE9 SVG, needs conditional override of 'filter' to 'none' */
			background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZjZWNmYyIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjUwJSIgc3RvcC1jb2xvcj0iI2ZiYTZlMSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjUxJSIgc3RvcC1jb2xvcj0iI2ZkODlkNyIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNmZjdjZDgiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
			background: -moz-linear-gradient(top,  #fcecfc 0%, #fba6e1 50%, #fd89d7 51%, #ff7cd8 100%); /* FF3.6+ */
			background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fcecfc), color-stop(50%,#fba6e1), color-stop(51%,#fd89d7), color-stop(100%,#ff7cd8)); /* Chrome,Safari4+ */
			background: -webkit-linear-gradient(top,  #fcecfc 0%,#fba6e1 50%,#fd89d7 51%,#ff7cd8 100%); /* Chrome10+,Safari5.1+ */
			background: -o-linear-gradient(top,  #fcecfc 0%,#fba6e1 50%,#fd89d7 51%,#ff7cd8 100%); /* Opera 11.10+ */
			background: -ms-linear-gradient(top,  #fcecfc 0%,#fba6e1 50%,#fd89d7 51%,#ff7cd8 100%); /* IE10+ */
			background: linear-gradient(to bottom,  #fcecfc 0%,#fba6e1 50%,#fd89d7 51%,#ff7cd8 100%); /* W3C */
			filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fcecfc', endColorstr='#ff7cd8',GradientType=0 ); /* IE6-8 */
		}
		</style>
		<!--[if gte IE 9]>
		<style type="text/css">
			.linksList ul li.lit, #main_link, .ftitle_bg, .listTitle, #exp_main .title, .menu_bg, .btn_bg, .btn_bg2, .footer_bottom{
				filter: none;
			}
		</style>
		<![endif]-->
	</head>
	<body>
		<div id="web_main">
			<div id="main_top"><div id="cdate"></div></div>
			<div id="main_menu_bg" class="menu_bg">
				<div id="main_menu">
					<ul>
						<?php 
						$lmuAry = $this->_chkf->getAry();
						foreach ($lmuAry as $key => $valAry):if ($valAry["active"] == "Y"):?>
						<li class="btn_bg whcolor div_maru"><a href="/<?php echo $key;?>/"><?php echo $valAry["title"];?></a></li>
						<?php endif;endforeach;?>
					</ul>
				</div>
			</div>
			<div id="main_center">
				<div id="main_left">
					<div class="linksList"><ul><li class="lit">子選單</li>
					<?php if (in_array($this->_url_pathAry[1], array("about", "business", "member", "album", "exp"))):$data = $view->getData();
						if (in_array($this->_url_pathAry[2], array("detail"))):
							echo "<li class='lits whcolor'>" . implode("</li><li class='lits whcolor'>", $data -> item) . "</li>";
						else:
							echo "<li class='lits whcolor'>" . implode("</li><li class='lits whcolor'>", $data["item"]) . "</li>";
						endif;
					endif;?>
				</ul></div>
				<div id="left_link"><?php require_once LAYOUT_PATH . DS . "link.phtml";?></div>
				</div>
				<div id="main_right">
					<?php if ($this->_url_pathAry[1] != "home" && $this->_url_pathAry[1] != ""):?><div id="SITE_TITLE" class="ftitle_bg"><?php echo $this->_chkf->getFuName($this->_url_pathAry[1]);?></div><?php endif;?>
					<div><?php require_once TEMPLATE_PATH . DS . $this->assignTemplate . DS . $view->_myPage . ".phtml";?></div>
				</div>
				<div style="clear: both;"></div>
			</div>
		</div>
		<div class="clear_div"></div>
		<div id="footer" class="footer_bottom">
			<div id="footer_data">
			<?php echo $this->siteDatas -> SITE_CONFIG -> TITLE;?><br>
			電話:<?php echo $this->siteDatas -> SITE_CONFIG -> TEL;?> 傳真:<?php echo $this->siteDatas -> SITE_CONFIG -> FAX;?><br>
			電子郵件:<?php echo $this->siteDatas -> SITE_CONFIG -> EMAIL;?> 住址:<?php echo $this->siteDatas -> SITE_CONFIG -> ADDRESS;?><br>
			<?php echo nl2br($this->siteDatas -> SITE_CONFIG -> MEMOIRS);?>
			</div>
		</div>
	</body>
</html>