<html>
	<head>
		<title><?php echo $this->siteDatas -> SITE_CONFIG -> TITLE;?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php foreach ($this -> _controllCss as $cssFile):?><link rel="StyleSheet" href="/styles/<?php echo $cssFile;?>.css" type="text/css"><?php endforeach;?>
		<?php foreach ($this -> _controllJs as $jsFile):?><script type="text/javascript" src="<?php echo ((strtolower(substr($jsFile, 0, 4)) == "http") ? $jsFile : "/scripts/" . $jsFile);?>.js"></script><?php endforeach;?>
		<script type="text/javascript">
		$(function(){
			var weeksAry = new Array("星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六");
			var chineseDate = "<?php echo date("Y年m月d日");?>(" + weeksAry[<?php echo date(w);?>] + ") " + LunarDate.GetLunarDay(<?php echo date("Y, m, d");?>);
			$("#cdate").html(chineseDate);
		});
		</script>
	</head>
	<body>
		<div id="web_main">
			<div id="main_top"><div id="cdate"></div>
				<div id="main_menu">
					<ul>
						<?php 
						$lmuAry = $this->_chkf->getAry();
						foreach ($lmuAry as $key => $valAry):if ($valAry["active"] == "Y"):?>
						<li><a href="/<?php echo $key;?>/"><?php echo $valAry["title"];?></a></li>
						<?php endif;endforeach;?>
					</ul>
				</div>
			</div>
			<div id="main_center">
				<div id="main_left">
					<div id="left_link"><?php require_once LAYOUT_PATH . DS . "link.phtml";?></div>
				</div>
				<div id="main_right">
					<div id="SITE_TITLE" class="ftitle_bg"><?php echo $this->_chkf->getFuName($this->_url_pathAry[1]);?></div>
					<div><?php require_once TEMPLATE_PATH . DS . $this->assignTemplate . DS . $view->_myPage . ".phtml";?></div>
				</div>
				<div style="clear:both;"></div>
			</div>
		</div>
	</body>
</html>